# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters

version: 2

run:
  deadline: 3m
  concurrency: 8
  tests: true
  modules-download-mode: vendor
  go: ""

output:
  formats:
    colored-line-number: stdout
  print-issued-lines: false
  print-linter-name: true
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  exclude-files:
    - ".*_gen.go"

linters:
  disable-all: true
  fast: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    #    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - godot
    #    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

formatters:
  disable-all: true
  enable:
    - gofmt
    - gofumpt
    - goimports

linters-settings:
  # See https://go-critic.com/overview.html
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # These 3 will detect many cases, but they do sense
      # if it's performance oriented code
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

  errcheck:
    # Report `a := b.(MyStruct)` when `a, ok := ...` should be.
    check-type-assertions: true # Default: false

    # Report skipped checks:`num, _ := strconv.Atoi(numStr)`.
    check-blank: true # Default: false

    # Function to skip.
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    disable:
      - fieldalignment

  nakedret:
    max-func-lines: 1 # Default: 30

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab
